package com.github.anavarro.springstatemachinesample.workflow;

/**
 * Created by anavarro on 24/07/16.
 */
public enum SimplifiedWorkflowEvent {
//    STORING_RFQ,
//    STORING_PRICING_INFO,
//    SAVING_STATUS_NEW,
//    REQUESTING_BETA_USER_INFO,
//    SENDING_RFQ_TO_DEFAULT_PRICER,
//    SAVING_PRICING_ACK_INFO,
//    CANCELLING_RFQ,
//    SAVING_PRICING_OTHER_INFO,
//    APPLYING_MARGIN,
//    DEFAULTING_BOOKING_INFO,
//    REQUESTING_PDC_CALCULATION,
//    FETCHING_PDC_RESULT,
//    SENDING_TRANSACTION_TO_ONYX_REQUEST



    // Use choiced in external to go from a state to another, is it better?
    SAVING_RFQ_TO_REQUEST_EVENT,
    SAVING_PRICING_INFO_TO_CLIENT_PRICING_EVENT,
    ASKING_IS_BETA_TO_USER_EVENT,
    ASKING_PRICE_TO_TRADER_PRICER_EVENT,
    RECEIVING_PRICE_FROM_TRADER_PRICER_EVENT,
    CANCELLING_RFQ_EVENT,
    SAVING_PRICING_OTHER_INFO_TO_BOOKING_EVENT,
    APPLYING_MARGIN_TO_CLIENT_PRICING_EVENT,
    DEFAULTING_BOOKING_INFO_TO_BOOKING_EVENT,
    ASKING_PDC_COMPUTATION_TO_RISKY_EVENT,
    RECEIVING_PDC_COMPUTATION_FROM_RISKY_EVENT,
    SENDING_TRANSACTION_TO_REQUEST_EVENT


}
