package com.github.anavarro.springstatemachinesample.workflow;

/**
 * Created by anavarro on 23/07/16.
 */
public enum WorkflowEvent {
    STORING_RFQ,
    STORING_PRICING_INFO,
    SAVING_STATUS_NEW,
    REQUESTING_BETA_USER_INFO,
    SENDING_RFQ_TO_DEFAULT_PRICER,
    SAVING_PRICING_ACK_INFO,
    CANCELLING_RFQ,
    SAVING_PRICING_OTHER_INFO,
    APPLYING_MARGIN,
    DEFAULTING_BOOKING_INFO,
    REQUESTING_PDC_CALCULATION,
    FETCHING_PDC_RESULT,
    SENDING_TRANSACTION_TO_ONYX_REQUEST

}
