package com.github.anavarro.springstatemachinesample.workflow;

/**
 * Created by anavarro on 23/07/16.
 */
public enum WorkflowState {
    INITIATED,
    RFQ_STORAGE_SUCCEEDED,
    PRICING_INFO_STORAGE_SUCCEEDED,
    LIFE_SAVING_SUCCEEDED,
    BETA_USER_CONFIRMED,
    BETA_USER_DENIED,
    OTC_QUOTE_REQUEST_ACCEPTED,
    QUOTE_REQUEST_CANCELLED,
    PRICING_ACK_INFO_SAVING_SUCEEDED,
    OTC_QUOTED,
    PRICING_OTHER_INFO_SAVING_SUCCEEDED,
    MARGIN_RESPONSE_RECEIVED,
    DEFAULT_BOOKING_INFO_REQUEST_SUCCEEDED,
    PDC_CALCULATION_REQUEST_SUCCEEDED,
    PDC_RESULT_REQUEST_SUCCEEDED,
    TRANSACTION_SENT_ACKNOWLEDGED

}
